# -*- coding: utf-8 -*-
"""URLlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AkcN8Kq3QhdR6lDxwpwQTrxikcutY3QV
"""

import urllib.request

urllib.request.urlretrieve("http://raw.githubusercontent.com/AceJugaad/DL/main/prac_2.py","prac_2")